//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int MetodoPagoId { get; set; }
    
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
